### ISSUE TITLE
`/musicxml-to-svg` without saving files to the server?

### ISSUE THREAD

**Issue by max-y-huang** [max-y-huang/Schmilblick#15]
Can we explore if it's possible to modify the `/musicxml-to-svg` endpoint to not save any files on the server?

Possible lead:
* https://stackoverflow.com/questions/50736447/consume-content-of-the-file-without-saving-the-file-with-express-js

**Comment by ngtr6788** [comment]
Sure thing, word of warning from the docs: https://expressjs.com/en/resources/middleware/multer.html
"WARNING: Uploading very large files, or relatively small files in large numbers very quickly, can cause your application to run out of memory when memory storage is used."
Are you guys fine with this?

**Comment by max-y-huang** [comment]
> Sure thing, word of warning from the docs: https://expressjs.com/en/resources/middleware/multer.html "WARNING: Uploading very large files, or relatively small files in large numbers very quickly, can cause your application to run out of memory when memory storage is used." Are you guys fine with this?

@ngtr6788 `.mxl` files seem to be very well compressed (i.e. compare the sizes of the sample `.mxl` files vs their `.xml` counterparts), so I don't think the file size should be an issue. I also doubt we'd be processing too many files in quick succession.

**Comment by ngtr6788** [comment]
Got it!
